name: CI

on:
  push:
  pull_request:
    branches: [ "main", "develop" ]

env:
  GO_VERSION: 1.24.4

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install golang
      run: |
        set -eux
        cd /opt/
        curl -OL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
        sha256sum go${GO_VERSION}.linux-amd64.tar.gz
        sudo mkdir -p /usr/local/go-${GO_VERSION}
        sudo tar -C /usr/local/go-${GO_VERSION} -xvf go${GO_VERSION}.linux-amd64.tar.gz
        rm -rf /opt/go${GO_VERSION}.linux-amd64.tar.gz
        echo "/usr/local/go-${GO_VERSION}/go/bin" >> $GITHUB_PATH
    - name: Test
      run: make test
    - name: Build
      run: make build
    - name: Create DB Migrate File
      run: make dbmigrate
